server:
  port: 3344
spring:
  application:
    name: springcloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/darth-xiaozhijun/springcloud-geekshow-config.git
          search-paths:
            - springcloud-geekshow-config
      label: master

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'